{% set name = "thewalrus" %}
{% set version = "0.20.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/XanaduAI/thewalrus/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1a06309ac0e6895b7c2c9aab44473296e7626235fe823eaf7cd30c90550c053e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
  host:
    - numpy >=1.19.2
    - pip
    - python >=3.7
  run:
    - dask
    - numba >=0.49.1
    - {{ pin_compatible('numpy') }}
    - python >=3.7
    - scipy >=1.2.1
    - sympy >=1.5.1

test:
  imports:
    - thewalrus
  commands:
    - pip check
    - pytest --randomly-seed=137 thewalrus/tests
  requires:
    - pip
    - pytest
    - pytest-randomly
  source_files:
    - thewalrus/tests

about:
  home: https://github.com/XanaduAI/thewalrus
  summary: Open source library for hafnian calculation
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://the-walrus.readthedocs.io/

extra:
  recipe-maintainers:
    - BastianZim
